/**
 * Advance management
 * Advance project
 *
 * OpenAPI spec version: 0.0.1
 * Contact: ggenier@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Phone { 
    phoneType: Phone.PhoneTypeEnum;
    numero?: string;
}
export namespace Phone {
    export type PhoneTypeEnum = 'PERSO' | 'PROF' | 'MOBI' | 'AUTR';
    export const PhoneTypeEnum = {
        PERSO: 'PERSO' as PhoneTypeEnum,
        PROF: 'PROF' as PhoneTypeEnum,
        MOBI: 'MOBI' as PhoneTypeEnum,
        AUTR: 'AUTR' as PhoneTypeEnum
    };
}
