/**
 * Advance management
 * Advance project
 *
 * OpenAPI spec version: 0.0.1
 * Contact: ggenier@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Skill { 
    id?: number;
    skillType: Skill.SkillTypeEnum;
    certifie?: boolean;
}
export namespace Skill {
    export type SkillTypeEnum = 'TOIT' | 'ENDU' | 'HUIS';
    export const SkillTypeEnum = {
        TOIT: 'TOIT' as SkillTypeEnum,
        ENDU: 'ENDU' as SkillTypeEnum,
        HUIS: 'HUIS' as SkillTypeEnum
    };
}
